### ISSUE TITLE
ロゴがない

### ISSUE THREAD

**Issue by b-kaxa** [shalman/A-plus#1]
作ろう

**Comment by b-kaxa** [comment]
仮で作った

**Comment by b-kaxa** [comment]
おしまい

**Comment by shalman** [comment]
8bitっぽい。お疲れさまです。
暫定で。デザインこだわりたいので複数作って協議しましょう。

**Comment by b-kaxa** [comment]
ジェネレーターで30秒で作ったものなので適当に差し替えてもらっても大丈夫です
issueのcloseは俺がしちゃっていいのかな？shalmanが確認してcloseするっていう形にする？

**Comment by shalman** [comment]
確認の意味も込めて今後は僕がcloseしますー
