### ISSUE TITLE
クラスタグのAjax化

### ISSUE THREAD

**Issue by shalman** [shalman/A-plus#10]
現在getでクラスタグを付与しているのでjQueryのAjaxを用いて遷移しないようにする

**Comment by b-kaxa** [comment]
画面遷移しないということはレビューページにタグ一覧がないとだめな気がするけど、、、

**Comment by b-kaxa** [comment]
lightbox風ならやれそう

**Comment by shalman** [comment]
input/textの「新しくタグ追加」のとこのみAjaxで実装してみます。完了したらトーストっぽいデザインのウィンドウで完了orエラー通知
タグ一覧からはページ遷移で。

**Comment by b-kaxa** [comment]
http://fabien-d.github.io/alertify.js/
これ使いやすくていいと思う

**Comment by shalman** [comment]
右から来るの非常にkool
対応してみますー
