### ISSUE TITLE
人気検索ワードランキングから検索結果に飛べるようにする

### ISSUE THREAD

**Issue by b-kaxa** [shalman/A-plus#14]

**Comment by shalman** [comment]
現状、クエリパラメータにq=""だけ指定しても_tokenを入れないと検索対象にならないです。
検索をいたずら的に使うユーザーも懸念されるので、人気検索ワードランキング自体viewに表示させず、DBだけ保存して管理側だけの確認でいいかもしれません。
リリース後、様子見て復活もあり。

**Comment by shalman** [comment]
一旦クローズ。

**Comment by b-kaxa** [comment]
今、飛べるようになっているから外した方がいいかも
