### ISSUE TITLE
レビュー入力 ユーザビリティエンハンス

### ISSUE THREAD

**Issue by shalman** [shalman/A-plus#16]
* レビューがすべてプルダウンだと、ユーザーがレビューしにくい。
* プルダウンを極力しない。例えば、評価度(星)なら視覚的に星をクリックして評価する。
* プルダウンする場合は、スタイルでプルダウンメニューを大きくして、選択しやすくする。

**Comment by shalman** [comment]
画一情報(最終評価が試験orレポートなど決まった情報)は授業メインページでワンクリックで投票させた方が率上がりそう。。

**Comment by b-kaxa** [comment]
とりあえず動くか手元で確認よろしく

> 授業メインページでワンクリック

これは同意ですね、まあただこれ以上レビューページがごちゃごちゃするとあれなので整理が必要

**Comment by shalman** [comment]
お疲れ様です。確認しましたすばらしい。
ちょっとビューに関しては抜本的に見直したいと思ってます。(ゼロベースでないので安心してください。)
詳しくはSlackですりあわせましょう。

**Comment by b-kaxa** [comment]
tabがいいかもしれない
http://zxcvbnmnbvcxz.com/demonstration/tab/

**Comment by b-kaxa** [comment]
スマホ対応辛そう

**Comment by shalman** [comment]
レビューページは入力させるUI減らしてからcloseします。
トップページで投票っぽくajaxで追加予定
