### ISSUE TITLE
シラバスの導線

### ISSUE THREAD

**Issue by shalman** [shalman/A-plus#20]
* class/index/{id}からシラバスに飛ぶ導線をつける。
* 早稲田のシラバスはphpファイルにクエリパラメータをつけて識別していて、以下の通り。
例)pKey=1930000001042015193000000119&pLng=jp
* pKeyに関しては科目キー+クラスNo+年度+科目キー+学部コード(人科=19)の組み合わせの模様。

**Comment by b-kaxa** [comment]
変数のところ、定数化したいけどとりあえず

**Comment by b-kaxa** [comment]
> 細かいけど、本家より公式のほうがいいと思った
> あと、授業情報が確実に正しいわけではないからシラバス見ろよみたいな文言を入れないと。
> tab1に一つ公式の評価の円グラフ入れよう

**Comment by b-kaxa** [comment]
シラバスの導線自体はこれで終わりだと思うのでcloseします
