### ISSUE TITLE
検索結果のビューで総合平均評価の星を出す

### ISSUE THREAD

**Issue by shalman** [shalman/A-plus#25]
レビューがあれば出して、ない場合は灰色or出さない。

**Comment by b-kaxa** [comment]
とりあえず出来たのでcheckよろしくお願いします

**Comment by shalman** [comment]
Ajaxを使わずに、SQLのAVG使って計算して、phpからjsに動的にパラメータ渡した方がいいと思うのでちょっと僕の方で修正します。

**Comment by shalman** [comment]
動いてる&優先度が低かったので一旦close
