### ISSUE TITLE
LPがダサい

### ISSUE THREAD

**Issue by shalman** [shalman/A-plus#39]
* Top下部に、使い方、インフォメーションを表示。

**Comment by shalman** [comment]
インフォ(NEWS)などはCMSを使ったほうがいいかも。サブドメインに飛ばしてWordpressで管理など。リリースまでは静的コンテンツを用意。

**Comment by b-kaxa** [comment]
更新管理crudとかあればよいのでは

**Comment by shalman** [comment]
いい感じのCrudあれば使おうと思います。NEWS更新の作業は他のメンバーに振りたい。
リリース後に話し合いましょう。

**Comment by b-kaxa** [comment]
ごめん、自作すればって意味だった。

**Comment by shalman** [comment]
なるほど。でも汎用CRUDツールをgithubから探して使ってもいいですね
勉強としてyota氏に作ってもらうのもありかも。

**Comment by b-kaxa** [comment]
python crud mysql とかで検索

**Comment by sunmyinf** [comment]
たぶんDjangoとか使う感じになるかも、、？
頑張ります
