### ISSUE TITLE
時間割機能

### ISSUE THREAD

**Issue by shalman** [shalman/A-plus#65]
* classページにお気に入り時間割に登録するボタン配置
* マイページにマイ時間割のページ導線つくる

**Comment by sunmyinf** [comment]
これやります。
DBの設計もやってるし、同時にできることしておく。

**Comment by shalman** [comment]
ありがたい。これができるとiOS側にも機能拡張ができるので優先度高めで。

**Comment by sunmyinf** [comment]
ユーザー情報と時間割&履修授業&レビュー履歴のページを分ける

**Comment by shalman** [comment]
基本形ができたのでclose
