### ISSUE TITLE
スマホ時のハンバーガーメニュー

### ISSUE THREAD

**Issue by b-kaxa** [shalman/A-plus#9]
今のレスポンシブだとダサい

**Comment by b-kaxa** [comment]
headerをSCHEMA UI本家のモノに差し替えるとそのままいけそう

**Comment by b-kaxa** [comment]
これ使います
https://formstone.it/

**Comment by b-kaxa** [comment]
上手くいかないので考えます

**Comment by b-kaxa** [comment]
https://github.com/codrops/AnimatedBorderMenus

**Comment by b-kaxa** [comment]
しんどい

**Comment by shalman** [comment]
refs c5ae63430da4df0c2a07bca314e739fbf278c2da

**Comment by shalman** [comment]
そんなにしんどくなかった
